sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t zhenweifeng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zhenweifeng/react-test npm test

after_success:
  - docker build -t zhenweifeng/multi-client ./client
  - docker build -t zhenweifeng/multi-nginx ./nginx
  - docker build -t zhenweifeng/multi-server ./server
  - docker build -t zhenweifeng/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zhenweifeng/multi-client
  - docker push zhenweifeng/multi-nginx
  - docker push zhenweifeng/multi-server
  - docker push zhenweifeng/multi-worker